/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface JcSwiper {
    'loop': boolean;
    'speed': number;
  }
  interface JcSwiperAttributes extends StencilHTMLAttributes {
    'loop'?: boolean;
    'speed'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'JcSwiper': Components.JcSwiper;
  }

  interface StencilIntrinsicElements {
    'jc-swiper': Components.JcSwiperAttributes;
  }


  interface HTMLJcSwiperElement extends Components.JcSwiper, HTMLStencilElement {}
  var HTMLJcSwiperElement: {
    prototype: HTMLJcSwiperElement;
    new (): HTMLJcSwiperElement;
  };

  interface HTMLElementTagNameMap {
    'jc-swiper': HTMLJcSwiperElement
  }

  interface ElementTagNameMap {
    'jc-swiper': HTMLJcSwiperElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
